### ISSUE TITLE
No button appears

### ISSUE THREAD

**Issue by lobsterkatie** [wraithan/github-repo-widget#28]
Running FF 41.0.1 on OSX 10.10.5. Installed, no button appears. Would totally love this add-on if it worked!!

Thanks,
Katie

**Comment by wraithan** [comment]
Whoa, it has been like 4 years since I thought about this project. I should update it since I'm a lot better at JS than I was. Thanks for the report. No promises of a release anytime soon but I'll try.

**Comment by MutantOctopus** [comment]
I agree with this. I was interested to look at it but it seems sadly unfunctional at the moment. Subscribing for notifications.

**Comment by lobsterkatie** [comment]
Closing this, as I've long since moved to Chrome.
